/*



import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfHelper {
  static Future<void> createPdf(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    // Load logo
    final logoBytes = await rootBundle.load('assets/logo.png');
    final logo = pw.MemoryImage(logoBytes.buffer.asUint8List());

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(25),
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              // ----- LOGO -----
              pw.Center(
                child: pw.Image(logo, width: 120),
              ),
              pw.SizedBox(height: 20),

              // ----- TITLE -----
              pw.Text(
                "التقرير التفصيلي",
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 20),

              // ----- STYLED TABLE -----
              pw.Table(
                border: pw.TableBorder.all(
                  color: PdfColors.grey700,
                  width: 1.2,
                ),
                children: [
                  // header
                  pw.TableRow(
                    decoration: pw.BoxDecoration(color: PdfColors.grey300),
                    children: [
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text(
                          "Key",
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold, fontSize: 14),
                        ),
                      ),
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text(
                          "Value",
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold, fontSize: 14),
                        ),
                      ),
                    ],
                  ),
                  ...data.entries.map(
                        (e) => pw.TableRow(
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey100,
                      ),
                      children: [
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(
                            e.key.toString(),
                            style: const pw.TextStyle(fontSize: 13),
                          ),
                        ),
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(
                            e.value.toString(),
                            style: const pw.TextStyle(fontSize: 13),
                          ),
                        ),
                      ],
                    ),
                  )
                ],
              ),

              pw.SizedBox(height: 20),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  "Generated by Fils App",
                  style: pw.TextStyle(
                    color: PdfColors.grey600,
                    fontSize: 12,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    // ----- Save to Downloads -----
    final downloadsDir = await getDownloadsDirectory(); // iOS + Android 13+
    Directory finalDir;

    // fallback for older Android devices
    if (downloadsDir == null) {
      finalDir = Directory("/storage/emulated/0/Download");
    } else {
      finalDir = downloadsDir;
    }

    final file = File("${finalDir.path}/report_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());

    print("📁 تم حفظ الملف في: ${file.path}");
  }
}
*/

import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/material.dart' as fl;
import 'package:printing/printing.dart';

class PdfHelper {
  static PdfColor pdfColorFromFlutter(fl.Color color) {
    return PdfColor(color.red / 255, color.green / 255, color.blue / 255);
  }

  static Future<void> createReportPdf(
    List<Map<String, dynamic>> reportList,
    String nameShop,
  ) async {
    final pdf = pw.Document();

    // ========== بناء صفحة PDF ==========
    final logoBytes = await rootBundle.load('assets/test/logo_splash_new.png');
    final logo = pw.MemoryImage(logoBytes.buffer.asUint8List());

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(25),
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            children: [
              pw.Center(child: pw.Image(logo, width: 120)),
              pw.SizedBox(height: 20),
              pw.Text(
                "Reports ${nameShop.toString()}",
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 20),

              pw.Table(
                border: pw.TableBorder.all(
                  width: 1.2,
                  color: PdfColors.grey700,
                ),
                columnWidths: {
                  0: pw.FlexColumnWidth(2),
                  1: pw.FlexColumnWidth(2),
                  // 2: pw.FlexColumnWidth(1),
                },
                children: [
                  pw.TableRow(
                    decoration: pw.BoxDecoration(color: PdfColors.grey300),
                    children: [
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text(
                          "Name",
                          style: pw.TextStyle(
                            fontSize: 14,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                      ),
                      pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text(
                          "Value",
                          style: pw.TextStyle(
                            fontSize: 14,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                      ),
                      /* pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text("Color", style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                      ),*/
                    ],
                  ),

                  ...reportList.map((item) {
                    return pw.TableRow(
                      decoration: pw.BoxDecoration(color: PdfColors.grey100),
                      children: [
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(item["name"].toString()),
                        ),
                        pw.Padding(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(item["value"].toString()),
                        ),
                        pw.Container(
                          height: 20,
                          color: PdfColor(
                            (item["color"].red / 255),
                            (item["color"].green / 255),
                            (item["color"].blue / 255),
                          ),
                        ),
                      ],
                    );
                  }),
                ],
              ),
            ],
          );
        },
      ),
    );

    // ============================
    //     عرض PDF قبل الحفظ
    // ============================

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );

    // ============================
    //      حفظ الملف بعد العرض
    // ============================

    final downloads = await getDownloadsDirectory();
    Directory dir;

    if (downloads == null) {
      dir = Directory("/storage/emulated/0/Download");
    } else {
      dir = downloads;
    }

    final file = File(
      "${dir.path}/report_${DateTime.now().millisecondsSinceEpoch}.pdf",
    );
    await file.writeAsBytes(await pdf.save());

    print("📁 تم حفظ الملف في: ${file.path}");
  }
}
