// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtqJi81eZ753atY75wh4JSPe1c5dJFyWU',
    appId: '1:883238961579:android:e672813a06072a0d1512ee',
    messagingSenderId: '883238961579',
    projectId: 'fils-6bf68',
    databaseURL: 'https://fils-6bf68-default-rtdb.firebaseio.com',
    storageBucket: 'fils-6bf68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhNGrR_ozE97th2TSpmKm2_DyjSvo7ns',
    appId: '1:883238961579:ios:ddf4fa720c75ec8e1512ee',
    messagingSenderId: '883238961579',
    projectId: 'fils-6bf68',
    databaseURL: 'https://fils-6bf68-default-rtdb.firebaseio.com',
    storageBucket: 'fils-6bf68.firebasestorage.app',
    iosClientId: '883238961579-b73765geq8c5iia62le07s3rhu6ghn5b.apps.googleusercontent.com',
    iosBundleId: 'com.app.fils',
  );
}
